import React from "react";
import { SummaryHeader } from "./SummaryHeader";
import { ImportantCommunications } from "./ImportantCommunications";
import { CategorySummaries } from "./CategorySummaries";
import { ActionItems } from "./ActionItems";

export const EmailSummary: React.FC = () => {
  return (
    <div className="bg-white flex max-w-[875px] flex-col items-stretch justify-center p-5">
      <div className="flex w-full flex-col max-md:max-w-full">
        <SummaryHeader />
        <ImportantCommunications />
        <CategorySummaries />
        <ActionItems />
        <footer className="self-stretch flex-1 shrink basis-[0%] w-full gap-2 text-sm text-[rgba(65,75,109,1)] font-normal leading-[1.2] mt-10 py-2 border-[rgba(234,246,244,1)] border-t max-md:max-w-full">
          This report was automatically generated by the Weekly Email Summary
          Automation.
        </footer>
      </div>
    </div>
  );
};
